# http_status_codes.py

HTTP_STATUS_CODES = {

    # --- 1xx Information ---
    100: "Continue",
    101: "Switching Protocols",
    102: "Processing",
    103: "Early Hints",

    # --- 2xx Succès ---
    200: "OK",
    201: "Created",
    202: "Accepted",
    203: "Non-Authoritative Information",
    204: "No Content",
    205: "Reset Content",
    206: "Partial Content",
    207: "Multi-Status",
    208: "Already Reported",
    210: "Content Different",
    226: "IM Used",

    # --- 3xx Redirection ---
    300: "Multiple Choices",
    301: "Moved Permanently",
    302: "Found",
    303: "See Other",
    304: "Not Modified",
    305: "Use Proxy",
    306: "Unused",
    307: "Temporary Redirect",
    308: "Permanent Redirect",
    310: "Too Many Redirects",

    # --- 4xx Erreurs Client ---
    400: "Bad Request",
    401: "Unauthorized",
    402: "Payment Required",
    403: "Forbidden",
    404: "Not Found",
    405: "Method Not Allowed",
    406: "Not Acceptable",
    407: "Proxy Authentication Required",
    408: "Request Timeout",
    409: "Conflict",
    410: "Gone",
    411: "Length Required",
    412: "Precondition Failed",
    413: "Request Entity Too Large",
    414: "Request-URI Too Long",
    415: "Unsupported Media Type",
    416: "Requested Range Not Satisfiable",
    417: "Expectation Failed",
    418: "I'm a Teapot",
    419: "Page Expired",
    421: "Misdirected Request",
    422: "Unprocessable Entity",
    423: "Locked",
    424: "Failed Dependency",
    425: "Too Early",
    426: "Upgrade Required",
    427: "Invalid Digital Signature",
    428: "Precondition Required",
    429: "Too Many Requests",
    431: "Request Header Fields Too Large",
    444: "No Response (Nginx)",
    449: "Retry With",
    450: "Blocked by Windows Parental Controls",
    451: "Unavailable For Legal Reasons",
    456: "Unrecoverable Error",
    495: "SSL Certificate Error (Nginx)",
    496: "SSL Certificate Required (Nginx)",
    497: "HTTP Request Sent to HTTPS Port (Nginx)",
    498: "Token Expired/Invalid",
    499: "Client Closed Request (Nginx)",

    # --- 5xx Erreurs Serveur ---
    500: "Internal Server Error",
    501: "Not Implemented",
    502: "Bad Gateway",
    503: "Service Unavailable",
    504: "Gateway Timeout",
    505: "HTTP Version Not Supported",
    506: "Variant Also Negotiates",
    507: "Insufficient Storage",
    508: "Loop Detected",
    509: "Bandwidth Limit Exceeded",
    510: "Not Extended",
    511: "Network Authentication Required",

    # --- Cloudflare ---
    520: "Unknown Error (Cloudflare)",
    521: "Web Server Is Down (Cloudflare)",
    522: "Connection Timed Out (Cloudflare)",
    523: "Origin Is Unreachable (Cloudflare)",
    524: "A Timeout Occurred (Cloudflare)",
    525: "SSL Handshake Failed (Cloudflare)",
    526: "Invalid SSL Certificate (Cloudflare)",
    527: "Railgun Error (Cloudflare)",
} 
